# Generated by Django 2.1 on 2018-08-12 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jukebox', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='artist_cover_image',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='video_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
